# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b43ac5fb8307267a4b12e03560d3e31d376a34ffe34e64b3d153064cd6ebc4c4185bd46c5140a519b2783d6daa488573e61894b6915833de9eecd4d61e3c1e8d

test:
  secret_key_base: bbbc9ee4f03943c7e78440aea51e3d921a2b5b05e78ab8de8a8633af7840836a59806321f56e4ad07ea7d7cd21e9ef80cc1f9d8b60fbd102de9f1e8427910091

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
